[package]
name = "alloyfs-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
alloyfs-proto.workspace = true
alloyfs-common.workspace = true
alloyfs-transport.workspace = true
tokio.workspace = true
futures.workspace = true
bytes.workspace = true
dashmap.workspace = true
thiserror.workspace = true
tracing.workspace = true
globset.workspace = true
notify.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true

[dev-dependencies]
alloyfs-agent.workspace = true
tempfile.workspace = true
tracing-subscriber.workspace = true
